import { library } from "@fortawesome/fontawesome-svg-core";
import { faFacebookF, faLinkedinIn } from "@fortawesome/free-brands-svg-icons";
import {
    faClock,
    faHouseUser,
    faQuestion,
    faSignInAlt,
    faHome,
    faInfoCircle,
    faTrashAlt,
    faCheck,
    faPlusSquare,
    faPlusCircle,
    faWrench,
    faArrowsAltH,
    faFaucet,
    faLeaf,
    faArrowCircleLeft,
    faArrowCircleRight,
    faEye,
    faEyeSlash,
    faUserPlus,
    faEdit,
    faCaretDown,
    faChevronRight,
    faChevronLeft,
    faSortUp,
    faTimesCircle,
    faExclamationTriangle,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { faCircle, faCheckCircle } from '@fortawesome/fontawesome-free-regular'

library.add(
    faClock,
    faHouseUser,
    faQuestion,
    faSignInAlt,
    faHome,
    faInfoCircle,
    faTrashAlt,
    faCheck,
    faPlusSquare,
    faLinkedinIn,
    faFacebookF,
    faPlusCircle,
    faWrench,
    faArrowsAltH,
    faFaucet,
    faLeaf,
    faArrowCircleLeft,
    faArrowCircleRight,
    faEye,
    faEyeSlash,
    faUserPlus,
    faEdit,
    faCaretDown,
    faChevronRight,
    faChevronLeft,
    faSortUp,
    faCircle,
    faCheckCircle,
    faTimesCircle,
    faExclamationTriangle,
);

export default FontAwesomeIcon;